version: "3.9"

services:
  sim:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sim
    image: isaacsim-zmq:local
    runtime: nvidia
    shm_size: "2gb"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - RUN_ID=${RUN_ID:-dev_run}
      - START_MODE=${START_MODE:-handshake}
      - ZMQ_PUB=tcp://0.0.0.0:5556
      - ZMQ_REP=tcp://0.0.0.0:5557
      - ZMQ_PUB_FPS=${ZMQ_PUB_FPS:-2}
      - RENDERER=${RENDERER:-Rasterizing}
    ports:
      - "${PUB_PORT:-5556}:5556"
      - "${REP_PORT:-5557}:5557"
    volumes:
      - isaac_ws:/workspace_ws
      - isaac_out:/out

volumes:
  isaac_ws:
    # static key; dynamic actual name
    name: "isaac_ws_${USER:-unknown}"
  isaac_out:
    name: "isaac_out_${USER:-unknown}"
